repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: mixed-line-ending
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        files: \.py$
        # --remove-all-unused-imports is not used until issue #14 is solved
        args: ["--in-place", "--expand-star-imports", "--remove-unused-variables"]
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 22.10.0
    hooks:
    -   id: black
